import { NextResponse } from "next/server";
import { z } from "zod";
import { generateCypher } from "@/lib/gemini";
import { guardCypher } from "@/lib/cypherGuard";
import { getDriver } from "@/lib/neo4j";
import { shape } from "@/lib/shape";
import { errorResponse, ErrorCode } from "@/lib/errors";
import { checkRate } from "@/lib/rateLimit";
import { createHash } from "crypto";

const BodySchema = z.object({
  question: z.string().min(1).max(400),
  cypher: z.string().optional(), // pre-generated cypher from Ollama path
});

// Simple in-memory cache: SHA256(question+schemaV1) → result, TTL 60s
const cache = new Map<string, { result: unknown; expiresAt: number }>();
const CACHE_TTL = 60_000;
const SCHEMA_VERSION = "v1";

function cacheKey(question: string): string {
  return createHash("sha256").update(question + SCHEMA_VERSION).digest("hex");
}

export async function POST(req: Request) {
  const ip = req.headers.get("x-forwarded-for")?.split(",")[0]?.trim() ?? "anon";
  if (!checkRate(ip)) return errorResponse(ErrorCode.RATE_LIMITED);

  let body: unknown;
  try {
    body = await req.json();
  } catch {
    return errorResponse(ErrorCode.GENERATION_FAILED, "Invalid request body.");
  }

  const parsed = BodySchema.safeParse(body);
  if (!parsed.success) {
    return errorResponse(ErrorCode.GENERATION_FAILED, "Invalid request body.");
  }

  const { question, cypher: prebuiltCypher } = parsed.data;

  // Cache check (only for server-generated Cypher paths)
  if (!prebuiltCypher) {
    const key = cacheKey(question);
    const cached = cache.get(key);
    if (cached && Date.now() < cached.expiresAt) {
      return NextResponse.json(cached.result);
    }
  }

  let cypher: string;
  let rationale: string;

  if (prebuiltCypher) {
    // Ollama path: Cypher was generated client-side; skip Gemini
    cypher = prebuiltCypher;
    rationale = "Query generated by local Ollama model.";
  } else {
    const apiKey =
      req.headers.get("x-user-groq-key") ||
      req.headers.get("x-user-gemini-key") || // legacy header, still accepted
      process.env.GROQ_API_KEY ||
      process.env.GEMINI_API_KEY; // legacy env var fallback
    if (!apiKey) return errorResponse(ErrorCode.QUOTA_EXHAUSTED);

    try {
      const out = await generateCypher({ question, apiKey });
      cypher = out.cypher;
      rationale = out.rationale;
    } catch (e: unknown) {
      const msg = String((e as Error)?.message ?? "");
      // Parse nested JSON errors from the Google SDK
      let innerMsg = msg;
      try {
        const parsed = JSON.parse(msg);
        innerMsg = parsed?.error?.message ?? parsed?.message ?? msg;
      } catch { /* not JSON, use as-is */ }

      const code = /429|quota|resource.?exhausted/i.test(innerMsg)
        ? ErrorCode.QUOTA_EXHAUSTED
        : /401|403|expired|invalid.*key|api.?key/i.test(innerMsg)
        ? ErrorCode.BAD_USER_KEY
        : ErrorCode.GENERATION_FAILED;
      return errorResponse(code, innerMsg);
    }
  }

  const guard = guardCypher(cypher);
  if (!guard.ok) return errorResponse(ErrorCode.VALIDATION_BLOCKED, guard.reason);

  const start = performance.now();
  const database = process.env.NEO4J_DATABASE ?? "neo4j";

  try {
    const driver = getDriver();
    const session = driver.session({ database });
    try {
      const result = await session.executeRead((tx) =>
        tx.run(guard.cypher, {})
      );
      const shaped = shape(result.records);
      const ms = Math.round(performance.now() - start);
      const response = {
        cypher: guard.cypher,
        rationale,
        nodes: shaped.nodes,
        edges: shaped.edges,
        rows: shaped.rows,
        meta: { ...shaped.meta, ms },
      };

      // Store in cache
      if (!prebuiltCypher) {
        const key = cacheKey(question);
        cache.set(key, { result: response, expiresAt: Date.now() + CACHE_TTL });
      }

      return NextResponse.json(response);
    } finally {
      await session.close();
    }
  } catch (e: unknown) {
    const msg = String((e as Error)?.message ?? "");
    const code = /[Tt]imeout|time.?out/.test(msg)
      ? ErrorCode.EXECUTION_TIMEOUT
      : ErrorCode.EXECUTION_FAILED;
    return errorResponse(code, msg);
  }
}
