"use client";

/**
 * Browser-side Ollama client.
 * Calls http://localhost:11434 directly from the browser.
 * Only used on desktop as a fallback when Gemini quota is exhausted.
 */

const OLLAMA_BASE = "http://localhost:11434";

const SYSTEM_PROMPT = `You are a Cypher query generator for a read-only Spotify graph in Neo4j.

GRAPH SCHEMA:
- (:Track { track_id, track_name, popularity, danceability, valence, acousticness })
- (:Artist { name })
- (:Album { name })
- (:Genre { name })

Relationships:
- (:Track)-[:PERFORMED_BY]->(:Artist)
- (:Track)-[:BELONGS_TO]->(:Album)
- (:Track)-[:HAS_GENRE]->(:Genre)

Rules:
- Read-only only. No CREATE, MERGE, SET, DELETE, DROP, etc.
- Always include LIMIT (default 500) unless aggregation query.
- Return ONLY valid JSON: { "cypher": "...", "rationale": "..." }`;

export async function generateCypherOllama(opts: {
  question: string;
  model?: string;
}): Promise<{ cypher: string; rationale: string }> {
  const model = opts.model ?? "llama3.1";

  const res = await fetch(`${OLLAMA_BASE}/api/chat`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      model,
      stream: false,
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: opts.question },
      ],
      format: "json",
    }),
  });

  if (!res.ok) {
    throw new Error(`Ollama request failed: ${res.status} ${res.statusText}`);
  }

  const data = await res.json();
  const content = data?.message?.content ?? "";

  let parsed: { cypher: string; rationale: string };
  try {
    parsed = JSON.parse(content);
  } catch {
    throw new Error(`Ollama returned non-JSON: ${content.slice(0, 200)}`);
  }

  if (!parsed.cypher) {
    throw new Error("Ollama response missing cypher field.");
  }

  return {
    cypher: parsed.cypher,
    rationale: parsed.rationale ?? "Query generated by local Ollama model.",
  };
}

export async function isOllamaAvailable(): Promise<boolean> {
  try {
    const res = await fetch(`${OLLAMA_BASE}/api/tags`, { signal: AbortSignal.timeout(2000) });
    return res.ok;
  } catch {
    return false;
  }
}
